<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <AssemblyName>KeelMatrix.CorsSpec.IntegrationTests</AssemblyName>
    <RootNamespace>KeelMatrix.CorsSpec.IntegrationTests</RootNamespace>
    <NoWarn>$(NoWarn);CS1591;CA1707;CA1861</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/KeelMatrix.CorsSpec/KeelMatrix.CorsSpec.csproj" />
  </ItemGroup>
</Project>
